version: "3.8"

services:
  flask:
    container_name: flaskapp-container
    build:
      context: ./flask-server
    ports:
      - 80:80
    volumes:
      - ./flask-server:/code
    tty: true

  postgres:
    container_name: postgres-database2
    build:
      context: ./postgres-database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-database/createPlayer.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-database:/root/code
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=academy
